#######
#Input
INPUT:
  ##### Resolution #####
  RESOLUTION:
    CHANNEL: 3
    HEIGHT: 800
    WIDTH: 800

  ##### Resize scale #####
  RESIZE_SCALE:
    MIN_SIZE: 800
    MAX_SIZE: 800

  ##### ROI pool size #####
  ROI_POOL_SIZE: 7

  ##### Batch size #####
  BATCH_SIZE: 18

  ##### Camera scale #####
  CAMERA_SCALE: 0.031

  ##### Filtered-scale (i.e. Train/Validation, Evaluation) #####
  FILTERED_SCALE:
    TRAIN_VAL:
      REFERENCE: [[0.42, 0.42], [1.26, 0.21], [0.21, 1.26]]
      POST_PROCESS: [[0.42, 0.42], [1.26, 0.21], [0.21, 1.26]]
    
    EVALUATE:
      REFERENCE: [[0.42, 0.42], [1.26, 0.21], [0.21, 1.26]]
      POST_PROCESS: [[0.42, 0.42], [1.26, 0.21], [0.21, 1.26]]


#########
#Dataset
DATASET:
  ##### Train/Validation #####
  TRAIN_VAL:
    NG: '/mnt/HDD/DataCenter/Battery/Datasets/DataAnnotations/POC_GX3C/ObjectDetection/COCO/Global/NG/V6_20241112/NG_multi_class_all.json'
    PASS: '/mnt/HDD/DataCenter/Battery/Datasets/DataAnnotations/POC_GX3C/ObjectDetection/COCO/Global/PASS/V7_20241112/PASS_multi_class.json'

  ##### Evaluation #####
  EVALUATE: '/mnt/HDD/DataCenter/LIOHO/Datasets/Data/backup/POC_latest_whole/Image1_2/20230703/orig_img'

  ##### Split ratio #####
  SPLIT_RATIO: 0.05

  ##### Transform augmentation #####
  TRANSFORM:
    COLOR:
      HUE: [0.1, 0.2, 0.3, 0.4, 0.5]
      CONTRAST: [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]
      SATURATION: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]
      BRIGHTNESS: [0.8, 0.9, 1.0, 1.1]
    FLIP:
      HORIZONTAL: True
      VERTICAL: True

  ##### Format #####
  FORMAT: 'coco'


#######
#MODEL
MODEL:
  ##### Backbone #####
  BACKBONE: 'vovnetv2_27'

  ##### Meta network #####
  META_NETWORK: 'fcos'

  ##### Task #####
  TASK: 'segmentation'


###################################
#Learning rate (i.e. LR) scheduler
LR_SCHEDULER:
  ##### Step #####
  STEP: [1000,]

  ##### Ratio #####
  RATIO: 0.1

  ##### Function #####
  FUNCTION: 'warmupmultistep_lr'


###########
#Optimizer
OPTIMIZER:
  ##### Momentum #####
  MOMENTUM: 0.9

  ##### Weight decay #####
  WEIGHT_DECAY: 0.0001

  ##### Function #####
  FUNCTION: 'adam'


######
#Loss
LOSS:
  ##### Alpha #####
  ALPHA: 0.25

  ##### Beta #####
  BETA: 0.5

  ##### Gamma #####
  GAMMA: 2

  ##### Function #####
  FUNCTION: 'ce'


########
#Device
DEVICE:
  ##### Seed distribution #####
  SEED: 0

  ##### GPU ID #####
  GPU: 0

  ##### Number of workers #####
  NUM_WORKERS: 8


########
#Export
EXPORT:
  ##### ONNX #####
  ONNX:
    INPUT_NAMES: ['input_image']
    OUTPUT_NAMES: [output_argmax]
    OPSET_VERSION: 11

  ##### Format #####
  FORMAT: 'onnx'


#################
#Evaluate period
EVALUATE_PERIOD: 100


##################
#Output directory
OUTPUT: '/mnt/HDD/DataCenter/LIOHO/Models/tmp'